### PR TITLE
Update people.json - New Image Link

### PR DESCRIPTION
**Pull request by digiBeLow**
Changed my profile image link as requested.

### CODE REVIEW

**Review by annarankin — CHANGES_REQUESTED** [review]
Hi @digiBeLow! It looks like there are some unintended spacing changes that are causing a noisy diff in this PR - this happens to me when I have my editor's "format-on-save" setting turned on. Would you mind updating this PR with only your additive changes to make merging easier on down the line? 🙏

**Comment by annarankin** [comment]
Hi @digiBeLow ! It looks like the upstream repository you made this PR with has somehow disappeared - would you like some help getting your info on the site?

**Comment by digiBeLow** [comment]
Hi @annarankin - not sure what you're referring to, but either way my info appears to be on the site already.

**Comment by annarankin** [comment]
Ah, excellent! I'll close out this PR 👍

**Pull request closed without merging**
