### PR TITLE
Update people.json

### PR DESCRIPTION
**Pull request by TyroTheRam**
Added Ty Rotheram

### CODE REVIEW

**Comment by annarankin** [comment]
Hiya @TyroTheRam! I'm helping out with reviews -- It looks like you may have format-on-save turned on in your editor and it resulted in a bunch of spacing noise in the diff - it'll make merging easier down the line if you can revert the formatting and include just your info ✨

**Comment by TyroTheRam** [comment]
Hi Anna,

Thanks for your response! I'm sorry but I'm not really sure how to do that!
Does this mean I'll have to redo the submission?

Thanks
Ty

**Comment by annarankin** [comment]
Hi @TyroTheRam - no worries, I can help out with that - after work today I'll take a look 👍

**Comment by TyroTheRam** [comment]
Thanks so much Anna!

Have a great day!😁

Ty

**Comment by annarankin** [comment]
Ah shoot, I don't think that worked - we've got some merge conflicts with new files as well now since some other PRs got merged and somehow my spacing update doesn't seem to have fixed anything 🤔  If you like, I can try making a new PR tonight with your info if that's easier! Git will be the end of me yet 😂

**Comment by TyroTheRam** [comment]
Oh god, I feel your pain there! I haven't used it in ages because I'm
clueless with it! That would be awesome if you could do that please, I hope
it's not too much of a bother!

Thanks,
Tyler

**Comment by annarankin** [comment]
Closing this as your info was added in a separate PR! :D

**Pull request closed without merging**
